name: Update API

on:
  schedule:
    - cron: '0 0 */1 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Request API
      run: python main.py
    - name: Commit Changes
      continue-on-error: true
      run: |
        git config --global user.name 'Bot'
        git config --global user.email '<>'
        git add .
        git commit -m "Update API result"
        git push
