name: Update API

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  autogen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Request AP
      run: python main.py
    - name: Commit Changes
      continue-on-error: true
      run: |
        git config --global user.name 'Bot'
        git config --global user.email '<>'
        git add .
        git commit -m "Update API result"
        git push